appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: ske46Gzk6cjqwRq1NWV931gGCBYhYqrHt1/gWtOuiDzvCoCAoF7zmrWI2KmgTzkiVZujHV7YVODbOWMGX6nuq127KyvspvgWNH0VLd79Jp7TjRosAu1Q/ppgqQzHeFfBZQ9qqc+J+muZzaVbM/A6XTdarw7oqErGmR5mkZ/ECl1bpxbxBwl8lLvL06mWzIQPEum3pFUVvXOYsZxeUOUEboQbg4L9F62c7Yser3qTGOafkl+DCY8E3PI0Ab6sbUIMdmk3cR7GFOm2PR0YJLk+vjZv5/mWUE64DTlvlWPBvd9CyyiDSsB/tX+BS2gi7rWLqHbQ13yhDKRfCne4mKkPyGCwS/xkb6HQWN1syD9NWcAjzwwWRJU7aofmR+SrSyJCTlWmadCcqKnfg6ttdp9qhquyTbSFGarMMsjHFRrLnUB8r+KygFKF0rSeqsFt0Fec8uHu0THvEdGfMCkyIZ3V35uJEu4/pbsch8phlP67VZhb8xZbFrkU/zQnmjEE6A6u4qtq9p2KLSWLdDqtLYslAspW488ncfUoNKxnhUjI+1ozaZoeOk5QsBb6VB+cPQxKxGH9T/mj+20mkJ711O76HYDvzJ0SZbtsaC0cniHxdNn8IeJ0MypdKop111wXmuFk4p/EbZby08ZfcfIeTSb49A1LfpLaRFkQ8ezEHeMdAu4=
conda_forge_output_validation: true
